<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<!-- main section for Products  -->
<body>
    <h2>
        Add Products
    </h2>
    <h2>Add products using this form</h2>
    <?php echo $this->tag->form("product/add"); ?>
    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->textfield(["name ","class"=>"form-control"]); ?>
    </p>
    <p>
        <label for="description">Description</label>
        <?php echo $this->tag->textfield(["description","class"=>"form-control"]); ?>
    </p>
    <p>
        <label for="tags">Tags</label>
        <?php echo $this->tag->textfield(["tags ","class"=>"form-control"]); ?>
    </p>
    <p>
        <label for="price">Price</label>
        <?php echo $this->tag->textfield(["price ","class"=>"form-control"]); ?>
    </p>
    <p>
        <label for="stock">Stock</label>
        <?php echo $this->tag->textfield(["stock ","class"=>"form-control"]); ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton(["ADD", 'class' => 'btn btn-primary']); ?>
    </p>
    <p>
    <?php echo  $this->tag->linkTo(['product/view', 'View Products', 'class' => 'btn btn-primary']);?>
    </p>
    <p>
        <?php echo  $this->tag->linkTo(['index', 'Homepage', 'class' => 'btn btn-primary']); ?>
    </p>
    </form>
</body>

</html>