<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<!-- main section for Orders  -->
<body>
    <h2>
        Add Orders
    </h2>
    <h2>Place orders using this form</h2>
    <?php echo $this->tag->form("order/add"); ?>
    <p>
        <label for="customer_name">Customer-Name</label>
        <?php echo $this->tag->textfield(["customer_name ","class"=>"form-control"]); ?>
    </p>
    <p>
        <label for="customer_address">Customer-Address	</label>
        <?php echo $this->tag->textfield(["customer_address ","class"=>"form-control"]); ?>
    </p>
    <p>
        <label for="zipcode">Zipcode</label>
        <?php echo $this->tag->textfield(["zipcode ","class"=>"form-control"]); ?>
    </p>
    <p>
        <label for="product_name">Product-name</label>
        <?php
        $product = $this->db->fetchAll(
            "SELECT * FROM products",
            \Phalcon\Db\Enum::FETCH_ASSOC
        );
     echo "   <select name='products' id='products'>";
        foreach ($product as $key => $value) {
         echo   "<option value=".$value['name'].">".$value['name']."</option>";
        }
        echo "</select>";
        ?>
    </p>
    <p>
        <label for="quantity">Quantity</label>
        <?php echo $this->tag->textfield(["quantity ","class"=>"form-control"]); ?>
    </p>
    <p>
        <?php echo $this->tag->submitButton(["Place Order", 'class' => 'btn btn-primary']); ?>
    </p>
    <p>
    <?php echo  $this->tag->linkTo(['order/show', 'View Orders', 'class' => 'btn btn-primary']);?>
    </p>
    <p>
        <?php echo  $this->tag->linkTo(['index', 'Homepage', 'class' => 'btn btn-primary']); ?>
    </p>
    </form>
</body>

</html>